### PR TITLE
Facilitating & adding pyLODE documentation

### PR DESCRIPTION
**Pull request by nicholascar**
* added ontology metadata to Brick.ttl to facilitate pyLODE documentation generation
* added HTML & CSS generated by pyLODE from Brick.ttl

### CODE REVIEW

**Comment by gtfierro** [comment]
Thanks for the PR! pyLODE looks to be very helpful. There are a couple changes I would like before I merge this in -- if these are beyond what you have time for, just let me know and I can schedule time to make them.

- [ ] Include the OWL ontology metadata in one of the Python source files so that it is added to Brick when we generate the ontology. [Here](https://github.com/BrickSchema/brick-owl-dl/blob/master/generate_brick.py#L149) would probably be an appropriate place to add the ontology metadata using RDFlib
- [ ] include instructions in the README for generating the docs with pyLODE
- [ ] add pyLODE to the [requirements.txt](https://github.com/BrickSchema/brick-owl-dl/blob/master/requirements.txt) file
- [ ] move the generated pyLODE files to a special folder (`generated-docs`?). One suggestion I have is including the style file in a `<style>` tag in the generated HTML to reduce the requirements for serving the file, but I understand if you want to keep that separate

**Comment by gtfierro** [comment]
I've added most of this metadata in #8 ; and pyLODE seems to be happy now when it builds. I'm going to close this PR for now, but let me know if you run into any more issues with the ontology definition!

**Comment by nicholascar** [comment]
Hi @gtfierro, Thanks for this. I'll be releasing an online client for pyLODE so it will be easier to test out ontology documentation: copy 'n paste the ontology RDF into a textbox online & submit. Will let you know when complete.

**Comment by gtfierro** [comment]
Beautiful! Looking forward to it

**Pull request closed without merging**
