### PR TITLE
Vocab update

### PR DESCRIPTION
**Pull request by jbkoh**
#### Add:
- Static_Pressure
- Thermal_Power
- Chilled_Water_System
- Hot_Water_System

#### Remove:
- CWS (not a useful synonym)
- Condensor (not a useful synonym especially it's a typo of Condenser.)

### CODE REVIEW

**Review by gtfierro — APPROVED** [review]
Looks great! Thanks for the PR

**Review by gtfierro — CHANGES_REQUESTED** [review]
Can you apply the tags from the old `CWS` to the new `Chilled Water System`?

You should only need to add the following to the equip definition:

```python
        "tagvalues": [
            [BRICK.hasTag, TAG.Water],
            [BRICK.hasTag, TAG.Chilled],
            [BRICK.hasTag, TAG.Equip],
        ],
```

It would be great if you could do the same for the `Hot Water System` as well

**Comment by jbkoh** [comment]
I can do it, but do we need `Equip` Tag? I think it's inherited from `Equipment` root class.

**Comment by gtfierro** [comment]
Short answer is yes, we do need it.

The reason why is two-fold:

1) the Python framework does not inherit the tags down, so you have to duplicate them in the definition. This could be taken care of in a future release; there's nothing fundamental in the way. I just didn't have time to write that code

2) You need to include all of the tags in each restriction; OWL doesn't perform any inheritance of the restrictions for us.

**Comment by jbkoh** [comment]
Thanks, I was curious about the latter part; I assumed OWL supports inheriting restrictions. I will update this PR later today.

Thanks!

**Comment by gtfierro** [comment]
What the restrictions do in Brick is define a class as equivalent to the set of entities who possess the requisite set of tags. Its probably appropriate to think of it as _mostly_ orthogonal to the subclass mechanisms: instances of subclasses will inherit the tags of the parent classes, but not vice-versa

**Comment by jbkoh** [comment]
@gtfierro I just added missing OWL rules for CWS and HWS.

**Review by gtfierro — APPROVED** [review]

**Pull request merged**
